const SET_TOKEN="SET_TOKEN";
const REMOVE_TOKEN="REMOVE_TOKEN";
const SET_CURRENT_USER="SET_CURRENT_USER";
const SET_CURRENT_MONTH="SET_CURRENT_MONTH";
const SET_CURRENT_YEAR="SET_CURRENT_YEAR";
const SET_CURRENT_DATA="SET_CURRENT_DATA";
const REQUEST_LOGIN="REQUEST_LOGIN";
const LOGIN_SUCCESSFULL="LOGIN_SUCCESSFULL";
const LOGIN_FAILURE="LOGIN_FAILURE";
const REMOVE_DATA="REMOVE_DATA";
const LOGOUT="LOGOUT";
const SET_DATA="SET_DATA";
const SET_USERS="SET_USERS";
const PUSH_DATA="PUSH_DATA";



export {
  LOGIN_FAILURE,
  LOGIN_SUCCESSFULL,
  REQUEST_LOGIN,
  SET_CURRENT_MONTH,
  SET_CURRENT_DATA,
  SET_CURRENT_YEAR,
  SET_CURRENT_USER,
  SET_TOKEN,
  REMOVE_TOKEN,
  REMOVE_DATA,
  LOGOUT,
  SET_USERS,
  SET_DATA,
  PUSH_DATA
}
